EX00=ex00
EX01=ex01
EX02=ex02
EX03=ex03
EX04=ex04
EX05=ex05
EX06=ex06
EX07=ex07
EX08=ex08
EX09=ex09
EX10=ex10
EX11=ex11
EX12=ex12
EX13=ex13
EX14=ex14
EX15=ex15
EX16=ex16
EX17=ex17

all: ${EX00} ${EX01} ${EX02} ${EX03} ${EX04} ${EX05} ${EX06} ${EX07} ${EX08} ${EX09} ${EX10} ${EX11} ${EX12} ${EX13} ${EX14} ${EX15} ${EX16} ${EX17}

#Con Make - C se ejecuta el make en la carpeta que le pasemos por parámetro
${EX00}:
	$(MAKE) -C ${EX00}

${EX01}:
	$(MAKE) -C ${EX01}

${EX02}:
	$(MAKE) -C ${EX02}

${EX03}:
	$(MAKE) -C ${EX03}

${EX04}:
	$(MAKE) -C ${EX04}

${EX05}:
	$(MAKE) -C ${EX05}

${EX06}:
	$(MAKE) -C ${EX06}

${EX07}:
	$(MAKE) -C ${EX07}

${EX08}:
	$(MAKE) -C ${EX08}

${EX09}:
	$(MAKE) -C ${EX09}

${EX10}:
	$(MAKE) -C ${EX10}

${EX11}:
	$(MAKE) -C ${EX11}

${EX12}:
	$(MAKE) -C ${EX12}

${EX13}:
	$(MAKE) -C ${EX13}

${EX14}:
	$(MAKE) -C ${EX14}

${EX15}:
	$(MAKE) -C ${EX15}

${EX16}:
	$(MAKE) -C ${EX16}

${EX17}:
	$(MAKE) -C ${EX17}



clean:
	$(MAKE) clean -C ${EX00}
	$(MAKE) clean -C ${EX01}
	$(MAKE) clean -C ${EX02}
	$(MAKE) clean -C ${EX03}
	$(MAKE) clean -C ${EX04}
	$(MAKE) clean -C ${EX05}
	$(MAKE) clean -C ${EX06}
	$(MAKE) clean -C ${EX07}
	$(MAKE) clean -C ${EX08}
	$(MAKE) clean -C ${EX09}
	$(MAKE) clean -C ${EX10}
	$(MAKE) clean -C ${EX11}
	$(MAKE) clean -C ${EX12}
	$(MAKE) clean -C ${EX13}
	$(MAKE) clean -C ${EX14}
	$(MAKE) clean -C ${EX15}
	$(MAKE) clean -C ${EX16}
	$(MAKE) clean -C ${EX17}

fclean: 
	$(MAKE) fclean -C ${EX00}
	$(MAKE) fclean -C ${EX01}
	$(MAKE) fclean -C ${EX02}
	$(MAKE) fclean -C ${EX03}
	$(MAKE) fclean -C ${EX04}
	$(MAKE) fclean -C ${EX05}
	$(MAKE) fclean -C ${EX06}
	$(MAKE) fclean -C ${EX07}
	$(MAKE) fclean -C ${EX08}
	$(MAKE) fclean -C ${EX09}
	$(MAKE) fclean -C ${EX10}
	$(MAKE) fclean -C ${EX11}
	$(MAKE) fclean -C ${EX12}
	$(MAKE) fclean -C ${EX13}
	$(MAKE) fclean -C ${EX14}
	$(MAKE) fclean -C ${EX15}
	$(MAKE) fclean -C ${EX16}
	$(MAKE) fclean -C ${EX17}

re:
	$(MAKE) re -C ${EX00}
	$(MAKE) re -C ${EX01}
	$(MAKE) re -C ${EX02}
	$(MAKE) re -C ${EX03}
	$(MAKE) re -C ${EX04}
	$(MAKE) re -C ${EX05}
	$(MAKE) re -C ${EX06}
	$(MAKE) re -C ${EX07}
	$(MAKE) re -C ${EX08}
	$(MAKE) re -C ${EX09}
	$(MAKE) re -C ${EX10}
	$(MAKE) re -C ${EX11}
	$(MAKE) re -C ${EX12}
	$(MAKE) re -C ${EX13}
	$(MAKE) re -C ${EX14}
	$(MAKE) re -C ${EX15}
	$(MAKE) re -C ${EX16}
	$(MAKE) re -C ${EX17}

.PHONY: all clean fclean re ${EX00} ${EX01} ${EX02} ${EX03} ${EX04} ${EX05} ${EX06} ${EX07} ${EX08} ${EX09} ${EX10} ${EX11} ${EX12} ${EX13} ${EX14} ${EX15} ${EX16} ${EX17}